version: '3.8'
services:
  web:
    image: '${GITLAB_IMAGE}'
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      SESOP_HOME: /srv/sesop
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - '$SESOP_HOME:/srv/sesop'
    shm_size: '256m'