version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:16.5.1-ce.0'
    restart: always
    hostname: 'git-home.local'
    environment:
      SESOP_HOME: /mnt/sesop
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git-home.local'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - '$SESOP_HOME:/mnt/sesop'
    shm_size: '256m'